export const INVADERS_TYPE_CODE_FLAG_GRUNT = "G1";
export const INVADERS_TYPE_CODE_SPEAR_GRUNT = "G2";
export const INVADERS_TYPE_CODE_SWORD_GRUNT = "G3";
export const INVADERS_TYPE_CODE_MUSKETEER = "M";
export const INVADERS_TYPE_CODE_WARRIOR = "W";
export const INVADERS_TYPE_CODE_BATTLE_MAGE = "BM";
